#!/bin/bash
#
# Copyright 2015 (c)
# Gabriel-Andrew Pollo Guilbert
#
# This is a simple script that clean the whole
# tree from unused files.
#
# SYNTAX
#
# To clean a the whole tree:
#     ./clean [OPTIONS...]

SUCCESS=0
ERROR=1
TARGET=

function help {
	echo -e "Usage: ./clean [OPTIONS...]"
	echo -e ""
	echo -e "Options:"
	echo -e "\t-h, --help:\t show this message"
}

function parse {
	for ARG in "$@"; do
		case "$ARG" in
		"-h" | "--help")
			help
			return $ERROR
			;;
		*)
			echo -e "Unrecognized option '$ARG'"
			echo -e "Try '--help' for more information."
			return $ERROR
			;;
		esac
	done

	return $SUCCESS
}

function main {
	parse $@

	for file in $(find ./ -iname "*.o"); do
		rm -v "$file"
	done

	for file in $(find ./ -wholename "*/bin/*"); do
		rm -v "$file"
	done
}

main $@
