#!/bin/bash
#
# Copyright 2015 (c)
# Gabriel-Andrew Pollo Guilbert
#
# This is a simple script that will compile
# and run a project.
#
# SYNTAX
#
# To run a project:
#     ./run <PROJECT'S PATH>

PROJECT=$1

if [[ ! -n $PROJECT ]]; then
	echo "ERROR: No project name given."
	exit 1
fi

cd $PROJECT

make mkdir
make
echo
if [[ $? == 0 ]]; then
	make run
else
	echo "ERROR: The project didn't compile."
fi
